- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true
    tags: di

- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true
    tags: di

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    tags: di
- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
    tags: di

- name: Update apt and install docker-ce
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    tags: di
  with_items:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io 
    - docker-compose-plugin

- name: Install Docker Module for Python
  pip:
    name: docker
    tags: di

- name: adding existing user to group docker
  user:
    name: cityhunter
    groups: docker
    append: yes
    tags: di