---
- name: Playbook
  hosts: webservers
  become: true
  gather_facts: no
  # vars_files: 
    # - /home/cityhunter/Desktop/DevOps/ansible/roles/grafana/vars/grafana_credentials.yml
    # - "{{ role_path }}/vars/grafana_credentials.yml"
  vars:
    ansible_python_interpreter: /usr/bin/python3 #ansible specify python interpreter
    container_count: 4
    default_container_name: docker
    default_container_image: ubuntu
    default_container_command: sleep 1
  roles: 
    - apache
    - docker-install
    - docker-task
    - docker-login
    - grafana
    