name: test operations
on:
  pull_request:
  push:
    branches: 
      - '**' 
jobs:
  test:
    name: Molecule
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2 #Once it builds ubuntu test environment it Checks out the code within the test environment

      - name: Set up Python 3
        uses: actions/setup-python@v2 #set up Python for me 
        with:
          python-version: '3.10.6'

      - name: Install test dependencies
        run: pip3 install 'molecule[docker]' yamllint ansible-lint molecule==1.25.1

      - name: Run molecule test
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

       